apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: much-to-do
data:
  mongo-init.js: |
    // Init script if needed, currently empty/placeholder
    db = db.getSiblingDB('much_todo_db');
