apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: much-to-do
data:
  PORT: "8080"
  DB_NAME: "much_todo_db"
  ENABLE_CACHE: "false" # Disabling Redis for simplicity in K8s unless explicitly requested to deploy Redis too
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  GIN_MODE: "release"
