apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: much-to-do
type: Opaque
data:
  # your-super-secret-key-that-is-long-and-random
  jwt-secret-key: eW91ci1zdXBlci1zZWNyZXQta2V5LXRoYXQtaXMtbG9uZy1hbmQtcmFuZG9t
